import { test, expect } from "@playwright/test";
import { LoginPage } from "../pageobjects/loginPage";
import { IssuePage } from "../pageobjects/IssuePage";
test("All tabs are displayed on the Home page", async ({ page }) => {
  const login = new LoginPage(page);
  const issuePage = new IssuePage(page);
  await login.userLogin();
  await issuePage.goToIssuePage();
  await issuePage.clickOverviewLink();
  await expect(await issuePage.isOnOverviewLinkPage()).toBe(true);
  await issuePage.clickDownloadLink();
  await expect(await issuePage.isOnDownloadPage()).toBe(true);
  await issuePage.clickActivityLink();
  await expect(await issuePage.isOnActivityPage()).toBe(true);
  await issuePage.clickRoadmapLink();
  await expect(await issuePage.isOnRoadmapPage()).toBe(true);
  await issuePage.clickIssuesLink();
  await expect(await issuePage.isOnIssuesPage()).toBe(true);
  await issuePage.clickNewsLink();
  await expect(await issuePage.isOnNewsPage()).toBe(true);
  await issuePage.clickWikiLink();
  await expect(await issuePage.isOnWikiPage()).toBe(true);
  await issuePage.clickForumsLink();
  await expect(await issuePage.isOnForumsPage()).toBe(true);
  await issuePage.clickRepositoryLink();
  await expect(await issuePage.isOnRepositoryPage()).toBe(true);
});
