# .github/workflows/playwright.yml
name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install
        npm install -D allure-playwright

    - name: Run tests
      run: |
        npx playwright install
        npx playwright test

    - name: Upload Allure Report
      uses: Allure-Framework/allure2-action@v2
      with:
        allure-results: 'allure-results'
